In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
input = cv2.imread("Images/yuvrajsingh.jpg", 0) # helps use to load an image  0 = Grey scale image and 1 = colour full image default = 1
input = cv2.resize(input , (1100 , 700)) #resizing the image
print(input)
cv2.imshow("Yuvraj Singh" , input) #displaying the image
cv2.waitKey()  # 
cv2.destroyAllWindows()

[[ 89  89  88 ...  51  53  56]
 [ 87  86  86 ...  50  53  55]
 [ 85  84  84 ...  50  53  55]
 ...
 [137 129 122 ... 130 133 136]
 [137 129 122 ... 130 134 136]
 [137 129 122 ... 130 133 136]]


### lets print the dimesnion of the image

In [4]:
print("Height of image" , int(input.shape[0] ), "pixels")
print("Weight of image" , int(input.shape[1] ), "pixels")

Height of image 700 pixels
Weight of image 1100 pixels


### here we save the images

In [5]:
cv2.imwrite("input.png" , input)
cv2.imwrite("input.jpg" , input)

True

###    Example 2

In [6]:
import cv2
data = cv2.imread("Images/Barack_Obama.jpg" , 0)
cv2.imshow("Input Image", data)
cv2.waitKey()
cv2.destroyAllWindows()
print(data.shape)

(1499, 1200)


### Example 3

In [7]:
import cv2
df = cv2.imread("Images/3v49raxlb8_WW187785.jpg", 1)
cv2.imshow("Data", df)
cv2.waitKey()
cv2.destroyAllWindows()
print(df.shape)

(480, 640, 3)


### Example 4

In [8]:
import cv2
d = cv2.imread("Images/MS-Dhoni-6.jpg")
cv2.imshow("Dhoni", d)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
import cv2
d = cv2.imread("Images/MS-Dhoni-6.jpg",)
cv2.imshow("Dhoni", d)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
# Image conversion project coloured image into grey scaled image

In [11]:
img = cv2.imread("Images/MS-Dhoni-6.jpg", 0)
img = cv2.resize(img , (1200 ,600))
cv2.imshow("Image" , img)


k = cv2.waitKey()
if k == ord("s"):
    cv2.imwrite("Dhoni Grey converted image.jpg" , img)
else:
    cv2.destroyAllWindows()